os: unstable

branches:
  except:
    - gh-pages

environment:
  GH_TOKEN:
    secure: fRRq3ihhnBA5DHzqNDqGCcB1KCBDpw2SbEfZk5foNG3b7nLXPmKZabi0zQhFpF0b
  nodejs_version: 7

cache:
  - node_modules -> package.json
  - app/node_modules -> app/package.json

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm install -g npm@latest > /dev/null
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install -s > /dev/null

test_script:
  - node --version
  - npm run lint
  - npm run test
  - npm run package-win
